[package]
name = "itsdns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-nal-async = { version = "0.3.0", path = "../../embedded-nal/embedded-nal-async" }
heapless = "0.7"
